spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost        # Redis server hostname
    port: 6379             # Redis server port
    password:              # Redis password if any
    database: 0            # Redis database index
    timeout: 5000ms        # Redis connection timeout
  application:
    rate-limiter:
      enabled: true        # Enable/disable the rate limiter
      window-size: 20      # Time window size in seconds for rate limiting
      limit: 2           # Maximum allowed requests per window per key
resilience4j:
  ratelimiter:
    instances:
      default:
        limit-for-period: 1             # Number of calls allowed per refresh period
        limit-refresh-period: 10s          # Refresh period (time window)
        timeout-duration: 0ms

logging:
  level:
    org.springframework.web.servlet.handler.HandlerMappingIntrospector: error
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
#    org.hibernate: debug
#    org.hibernate.SQL: debug
key: "2c59275423376651436c477e5c78344c36414468683473666e30613c3f40564c"
dummy-json: "https://dummyjson.com/products"